server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/
spring:
  application:
    name: zuul-server
#自定义路由规则，默认的规则依然生效
ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间
zuul:
  routes:
    api-index:
      path: /index/**
      serviceId: index-service
    api-product:
      path: /product/**
      serviceId: product-service
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题
  sensitive-headers:
  #默认zuul会屏蔽cookie，cookie不会传到下游服务，这里设置为空则取消默认的黑名单，表示会传递到下游服务，比如product-service