server:
  port: 8089
spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://106.13.197.193:3306/springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 517310
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
    type: mysql
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/