server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://106.13.197.193:3306/springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 517310
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

  application:
    name: product-service

---
  spring:
    profiles: productService1
  server:
    port: 8085
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/
      registry-fetch-interval-seconds: 30
    instance:
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
---
  spring:
    profiles: productService2
  server:
    port: 8086
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/
      registry-fetch-interval-seconds: 30
    instance:
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl