server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1358724404/MyFirst.git
